# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-28 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10, verbose_name='\u533a\u57df')),
            ],
        ),
        migrations.CreateModel(
            name='LikeStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styles', models.CharField(max_length=10, verbose_name='\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='\u4f4f\u5740')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('email', models.CharField(max_length=30, verbose_name='\u90ae\u7bb1')),
                ('gender', models.CharField(blank=True, choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, verbose_name='\u6027\u522b')),
                ('regions', models.ManyToManyField(blank=True, to='main.LikeRegion', verbose_name='\u610f\u5411\u533a\u57df')),
                ('styles', models.ManyToManyField(blank=True, to='main.LikeStyle', verbose_name='\u610f\u5411\u7c7b\u578b')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
