# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-01 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_id', models.IntegerField(verbose_name='\u63a8\u8350\u6307\u6570(\u586b\u5199\uff1a1\u30012\u30013...)')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('cover', models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('detail_url', models.CharField(max_length=100, verbose_name='\u8be6\u60c5\u94fe\u63a5')),
                ('limit_num', models.IntegerField(verbose_name='\u4eba\u6570\u4e0a\u9650')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8\u5217\u8868',
                'verbose_name_plural': '\u6d3b\u52a8\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='', upload_to=main.models.pic_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('detail_url', models.CharField(default='', max_length=100, verbose_name='\u8be6\u60c5\u94fe\u63a5')),
                ('recommend_id', models.IntegerField(verbose_name='\u63a8\u8350\u6307\u6570(\u586b\u5199\uff1a1\u30012\u30013...)')),
            ],
            options={
                'verbose_name': '\u9876\u90e8\u5e7f\u544a',
                'verbose_name_plural': '\u9876\u90e8\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_id', models.IntegerField(verbose_name='\u63a8\u8350\u6307\u6570(\u586b\u5199\uff1a1\u30012\u30013...)')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('cover', models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('location', models.CharField(blank=True, choices=[('jinjiang', '\u9526\u6c5f'), ('qingyangqu', '\u9752\u7f8a'), ('jinniu', '\u91d1\u725b'), ('wuhou', '\u6b66\u4faf'), ('chenghua', '\u6210\u534e'), ('gaoxing', '\u9ad8\u65b0\u533a'), ('gaoxingxiqu', '\u9ad8\u65b0\u897f\u533a'), ('wenjaing', '\u6e29\u6c5f'), ('shuangliu', '\u53cc\u6d41'), ('longquanyi', '\u9f99\u6cc9\u9a7f'), ('xindu', '\u65b0\u90fd'), ('pixian', '\u90eb\u53bf'), ('dujiangyan', '\u90fd\u6c5f\u5830'), ('qingbaijiang', '\u9752\u767d\u6c5f'), ('pengzhou', '\u5f6d\u5dde'), ('pujiang', '\u6d66\u6c5f'), ('dayi', '\u5927\u9091'), ('xinjin', '\u65b0\u6d25'), ('congzhou', '\u5d07\u5dde'), ('qionglai', '\u909b\u5d03'), ('jintang', '\u91d1\u5802')], max_length=70, verbose_name='\u4f4d\u7f6e')),
                ('metro', models.CharField(blank=True, choices=[('one', '1\u53f7\u7ebf'), ('two', '2\u53f7\u7ebf'), ('three', '3\u53f7\u7ebf'), ('four', '4\u53f7\u7ebf'), ('five', '5\u53f7\u7ebf'), ('seven', '7\u53f7\u7ebf'), ('eight', '\u6210\u704c\u5feb\u901f\u94c1\u8def')], max_length=10, verbose_name='\u5468\u8fb9\u5730\u94c1')),
                ('price_section', models.CharField(blank=True, choices=[('one', '3000\u4ee5\u4e0b'), ('two', '3000-5000'), ('three', '5000-7000'), ('four', '7000-9000'), ('five', '9000-11000'), ('size', '11000-15000'), ('seven', '15000-20000'), ('eight', '20000\u4ee5\u4e0a')], max_length=10, verbose_name='\u4ef7\u683c\u533a\u95f4')),
                ('building_type', models.CharField(blank=True, choices=[('one', '\u666e\u901a\u4f4f\u5b85'), ('two', '\u82b1\u56ed\u6d0b\u623f'), ('three', '\u522b\u5885'), ('four', '\u5546\u94fa'), ('five', '\u5199\u5b57\u697c'), ('six', '\u516c\u5bd3\uff09')], max_length=10, verbose_name='\u697c\u76d8\u7c7b\u578b')),
                ('area_section', models.CharField(blank=True, choices=[('one', '50\u33a1\u4ee5\u4e0b'), ('two', '50-70\u33a1'), ('three', '70-90\u33a1'), ('four', '90-110\u33a1'), ('five', '110-150\u33a1'), ('six', '150-200\u33a1'), ('seven', '200-300\u33a1'), ('eight', '300\u33a1\u4ee5\u4e0a')], max_length=15, verbose_name='\u9762\u79ef\u533a\u95f4')),
                ('open_date', models.DateField(verbose_name='\u5f00\u76d8\u65f6\u95f4')),
                ('detail_url', models.CharField(max_length=100, verbose_name='\u8be6\u60c5\u94fe\u63a5')),
                ('phone', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('price', models.FloatField(verbose_name='\u4ef7\u683c(\u5143)')),
            ],
            options={
                'verbose_name': '\u697c\u76d8\u5c55\u793a',
                'verbose_name_plural': '\u697c\u76d8\u5c55\u793a',
            },
        ),
        migrations.CreateModel(
            name='CollectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('\u624b\u673a', '\u624b\u673a'), ('\u771f\u5b9e\u59d3\u540d', '\u771f\u5b9e\u59d3\u540d'), ('\u5e74\u9f84', '\u5e74\u9f84'), ('\u8054\u7cfb\u5730\u5740', '\u8054\u7cfb\u5730\u5740')], max_length=10, verbose_name='\u5b57\u6bb5\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u586b\u5199\u5b57\u6bb5',
                'verbose_name_plural': '\u7528\u6237\u586b\u5199\u5b57\u6bb5',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('\u4e00\u5c45', '\u4e00\u5c45'), ('\u4e8c\u5c45', '\u4e8c\u5c45'), ('\u4e09\u5c45', '\u4e09\u5c45'), ('\u56db\u5c45', '\u56db\u5c45'), ('\u4e94\u5c45', '\u4e94\u5c45'), ('\u4e94\u5c45\u4ee5\u4e0a', '\u4e94\u5c45\u4ee5\u4e0a')], max_length=10, verbose_name='\u6237\u578b')),
            ],
            options={
                'verbose_name': '\u697c\u76d8\u6237\u578b',
                'verbose_name_plural': '\u697c\u76d8\u6237\u578b',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
                ('news_url', models.CharField(default='', max_length=200, verbose_name='\u94fe\u63a5')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u94fe\u63a5',
                'verbose_name_plural': '\u65b0\u95fb\u94fe\u63a5',
            },
        ),
        migrations.CreateModel(
            name='ParticipatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u9f84')),
                ('address', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53c2\u52a0\u8005\u4fe1\u606f',
                'verbose_name_plural': '\u53c2\u52a0\u8005\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u59d3\u540d')),
                ('gender', models.CharField(blank=True, choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u522b')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u9f84')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='\u4f4f\u5740')),
                ('regions', models.CharField(blank=True, choices=[('jinjiang', '\u9526\u6c5f'), ('qingyangqu', '\u9752\u7f8a'), ('jinniu', '\u91d1\u725b'), ('wuhou', '\u6b66\u4faf'), ('chenghua', '\u6210\u534e'), ('gaoxing', '\u9ad8\u65b0\u533a'), ('gaoxingxiqu', '\u9ad8\u65b0\u897f\u533a'), ('wenjaing', '\u6e29\u6c5f'), ('shuangliu', '\u53cc\u6d41'), ('longquanyi', '\u9f99\u6cc9\u9a7f'), ('xindu', '\u65b0\u90fd'), ('pixian', '\u90eb\u53bf'), ('dujiangyan', '\u90fd\u6c5f\u5830'), ('qingbaijiang', '\u9752\u767d\u6c5f'), ('pengzhou', '\u5f6d\u5dde'), ('pujiang', '\u6d66\u6c5f'), ('dayi', '\u5927\u9091'), ('xinjin', '\u65b0\u6d25'), ('congzhou', '\u5d07\u5dde'), ('qionglai', '\u909b\u5d03'), ('jintang', '\u91d1\u5802')], max_length=10, verbose_name='\u610f\u5411\u533a\u57df')),
                ('styles', models.CharField(blank=True, choices=[('one', '\u666e\u901a\u4f4f\u5b85'), ('two', '\u82b1\u56ed\u6d0b\u623f'), ('three', '\u522b\u5885'), ('four', '\u5546\u94fa'), ('five', '\u5199\u5b57\u697c'), ('six', '\u516c\u5bd3\uff09')], max_length=10, verbose_name='\u610f\u5411\u7c7b\u578b')),
                ('likes', models.ManyToManyField(to='main.Building', verbose_name='\u6536\u85cf\u7684\u697c\u76d8')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4e2d\u5fc3',
                'verbose_name_plural': '\u7528\u6237\u4e2d\u5fc3',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='house_type',
            field=models.ManyToManyField(to='main.HouseType', verbose_name='\u6237\u578b'),
        ),
        migrations.AddField(
            model_name='activity',
            name='collect_item',
            field=models.ManyToManyField(to='main.CollectItem', verbose_name='\u8bf7\u9009\u62e9\u60a8\u60f3\u6536\u96c6\u7684\u7528\u6237\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='activity',
            name='participator',
            field=models.ManyToManyField(blank=True, to='main.ParticipatorInfo', verbose_name='\u5df2\u62a5\u540d\u7528\u6237'),
        ),
    ]
