# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgurl', models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u94fe\u63a5')),
                ('imgname', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u7528\u6237\u4e2d\u5fc3', 'verbose_name_plural': '\u7528\u6237\u4e2d\u5fc3'},
        ),
        migrations.AddField(
            model_name='banner',
            name='newslimk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.News'),
        ),
    ]
