# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-01 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='weichat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5fae\u4fe1\u53f7'),
        ),
        migrations.AlterField(
            model_name='building',
            name='area_section',
            field=models.CharField(blank=True, choices=[('50\u33a1\u4ee5\u4e0b', '50\u33a1\u4ee5\u4e0b'), ('50-70\u33a1', '50-70\u33a1'), ('70-90\u33a1', '70-90\u33a1'), ('90-110\u33a1', '90-110\u33a1'), ('110-150\u33a1', '110-150\u33a1'), ('150-200\u33a1', '150-200\u33a1'), ('200-300\u33a1', '200-300\u33a1'), ('300\u33a1\u4ee5\u4e0a', '300\u33a1\u4ee5\u4e0a')], max_length=20, verbose_name='\u9762\u79ef\u533a\u95f4'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(blank=True, choices=[('\u666e\u901a\u4f4f\u5b85', '\u666e\u901a\u4f4f\u5b85'), ('\u82b1\u56ed\u6d0b\u623f', '\u82b1\u56ed\u6d0b\u623f'), ('\u522b\u5885', '\u522b\u5885'), ('\u5546\u94fa', '\u5546\u94fa'), ('\u5199\u5b57\u697c', '\u5199\u5b57\u697c'), ('\u516c\u5bd3', '\u516c\u5bd3\uff09')], max_length=20, verbose_name='\u697c\u76d8\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, choices=[('\u9526\u6c5f', '\u9526\u6c5f'), ('\u9752\u7f8a', '\u9752\u7f8a'), ('\u91d1\u725b', '\u91d1\u725b'), ('\u6b66\u4faf', '\u6b66\u4faf'), ('\u6210\u534e', '\u6210\u534e'), ('\u9ad8\u65b0\u533a', '\u9ad8\u65b0\u533a'), ('\u9ad8\u65b0\u897f\u533a', '\u9ad8\u65b0\u897f\u533a'), ('\u6e29\u6c5f', '\u6e29\u6c5f'), ('\u53cc\u6d41', '\u53cc\u6d41'), ('\u9f99\u6cc9\u9a7f', '\u9f99\u6cc9\u9a7f'), ('\u65b0\u90fd', '\u65b0\u90fd'), ('\u90eb\u53bf', '\u90eb\u53bf'), ('\u90fd\u6c5f\u5830', '\u90fd\u6c5f\u5830'), ('\u9752\u767d\u6c5f', '\u9752\u767d\u6c5f'), ('\u5f6d\u5dde', '\u5f6d\u5dde'), ('\u6d66\u6c5f', '\u6d66\u6c5f'), ('\u5927\u9091', '\u5927\u9091'), ('\u65b0\u6d25', '\u65b0\u6d25'), ('\u5d07\u5dde', '\u5d07\u5dde'), ('\u909b\u5d03', '\u909b\u5d03'), ('\u91d1\u5802', '\u91d1\u5802')], max_length=70, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='building',
            name='metro',
            field=models.CharField(blank=True, choices=[('1\u53f7\u7ebf', '1\u53f7\u7ebf'), ('2\u53f7\u7ebf', '2\u53f7\u7ebf'), ('3\u53f7\u7ebf', '3\u53f7\u7ebf'), ('4\u53f7\u7ebf', '4\u53f7\u7ebf'), ('5\u53f7\u7ebf', '5\u53f7\u7ebf'), ('7\u53f7\u7ebf', '7\u53f7\u7ebf'), ('\u6210\u704c\u5feb\u901f\u94c1\u8def', '\u6210\u704c\u5feb\u901f\u94c1\u8def')], max_length=20, verbose_name='\u5468\u8fb9\u5730\u94c1'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price_section',
            field=models.CharField(blank=True, choices=[('3000\u4ee5\u4e0b', '3000\u4ee5\u4e0b'), ('3000-5000', '3000-5000'), ('5000-7000', '5000-7000'), ('7000-9000', '7000-9000'), ('9000-11000', '9000-11000'), ('11000-15000', '11000-15000'), ('15000-20000', '15000-20000'), ('20000\u4ee5\u4e0a', '20000\u4ee5\u4e0a')], max_length=20, verbose_name='\u4ef7\u683c\u533a\u95f4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('\u7537', '\u7537'), ('\u7537', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regions',
            field=models.CharField(blank=True, choices=[('\u9526\u6c5f', '\u9526\u6c5f'), ('\u9752\u7f8a', '\u9752\u7f8a'), ('\u91d1\u725b', '\u91d1\u725b'), ('\u6b66\u4faf', '\u6b66\u4faf'), ('\u6210\u534e', '\u6210\u534e'), ('\u9ad8\u65b0\u533a', '\u9ad8\u65b0\u533a'), ('\u9ad8\u65b0\u897f\u533a', '\u9ad8\u65b0\u897f\u533a'), ('\u6e29\u6c5f', '\u6e29\u6c5f'), ('\u53cc\u6d41', '\u53cc\u6d41'), ('\u9f99\u6cc9\u9a7f', '\u9f99\u6cc9\u9a7f'), ('\u65b0\u90fd', '\u65b0\u90fd'), ('\u90eb\u53bf', '\u90eb\u53bf'), ('\u90fd\u6c5f\u5830', '\u90fd\u6c5f\u5830'), ('\u9752\u767d\u6c5f', '\u9752\u767d\u6c5f'), ('\u5f6d\u5dde', '\u5f6d\u5dde'), ('\u6d66\u6c5f', '\u6d66\u6c5f'), ('\u5927\u9091', '\u5927\u9091'), ('\u65b0\u6d25', '\u65b0\u6d25'), ('\u5d07\u5dde', '\u5d07\u5dde'), ('\u909b\u5d03', '\u909b\u5d03'), ('\u91d1\u5802', '\u91d1\u5802')], max_length=10, verbose_name='\u610f\u5411\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='styles',
            field=models.CharField(blank=True, choices=[('\u666e\u901a\u4f4f\u5b85', '\u666e\u901a\u4f4f\u5b85'), ('\u82b1\u56ed\u6d0b\u623f', '\u82b1\u56ed\u6d0b\u623f'), ('\u522b\u5885', '\u522b\u5885'), ('\u5546\u94fa', '\u5546\u94fa'), ('\u5199\u5b57\u697c', '\u5199\u5b57\u697c'), ('\u516c\u5bd3', '\u516c\u5bd3\uff09')], max_length=10, verbose_name='\u610f\u5411\u7c7b\u578b'),
        ),
    ]
