# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-30 03:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u9876\u90e8\u5e7f\u544a',
                'verbose_name_plural': '\u9876\u90e8\u5e7f\u544a',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_id', models.CharField(blank=True, choices=[('1', '\u4e00\u9897\u661f'), ('2', '\u4e24\u9897\u661f'), ('3', '\u4e09\u9897\u661f'), ('4', '\u56db\u9897\u661f'), ('5', '\u4e94\u9897\u661f')], max_length=5, verbose_name='\u63a8\u8350\u6307\u6570')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('cover', models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('location', models.CharField(blank=True, choices=[('qingyang', '\u9752\u7f8a'), ('jinniu', '\u91d1\u725b'), ('wuhou', '\u6b66\u4faf'), ('chenghua', '\u6210\u534e'), ('gaoxing', '\u9ad8\u65b0\u533a'), ('gaoxingxiqu', '\u9ad8\u65b0\u897f\u533a'), ('wenjaing', '\u6e29\u6c5f'), ('shuangliu', '\u53cc\u6d41'), ('longqianyi', '\u9f99\u6cc9\u9a7f'), ('xindu', '\u65b0\u90fd'), ('pixian', '\u90eb\u53bf'), ('dujiangyan', '\u90fd\u6c5f\u5830'), ('qingbaijiang', '\u9752\u767d\u6c5f'), ('pengzhou', '\u5f6d\u5dde'), ('pujiang', '\u6d66\u6c5f'), ('dayi', '\u5927\u9091'), ('xinjin', '\u65b0\u6d25'), ('zongzhou', '\u5d07\u5dde'), ('qonglai', '\u909b\u5d03'), ('jintang', '\u91d1\u5802')], max_length=70, verbose_name='\u4f4d\u7f6e')),
                ('metro', models.CharField(blank=True, choices=[('one', '1\u53f7\u7ebf'), ('two', '2\u53f7\u7ebf'), ('three', '3\u53f7\u7ebf'), ('four', '4\u53f7\u7ebf'), ('five', '5\u53f7\u7ebf'), ('seven', '7\u53f7\u7ebf'), ('chengguan', '\u6210\u704c\u5feb\u901f\u94c1\u8def')], max_length=10, verbose_name='\u5468\u8fb9\u5730\u94c1')),
                ('price_section', models.CharField(blank=True, choices=[('one', '3000\u4ee5\u4e0b'), ('two', '3000-5000'), ('three', '5000-7000'), ('four', '7000-9000'), ('five', '9000-11000'), ('size', '11000-15000'), ('seven', '15000-20000'), ('eight', '20000\u4ee5\u4e0a')], max_length=10, verbose_name='\u4ef7\u683c\u533a\u95f4')),
                ('building_type', models.CharField(blank=True, choices=[('one', '\u666e\u901a\u4f4f\u5b85'), ('two', '\u82b1\u56ed\u6d0b\u623f'), ('three', '\u522b\u5885'), ('four', '\u5546\u94fa'), ('five', '\u5199\u5b57\u697c'), ('six', '\u516c\u5bd3\uff09')], max_length=10, verbose_name='\u697c\u76d8\u7c7b\u578b')),
                ('area_section', models.CharField(blank=True, choices=[('one', '50\u33a1\u4ee5\u4e0b'), ('two', '50-70\u33a1'), ('three', '70-90\u33a1'), ('four', '90-110\u33a1'), ('five', '110-150\u33a1'), ('six', '150-200\u33a1'), ('seven', '200-300\u33a1'), ('eight', '300\u33a1\u4ee5\u4e0a')], max_length=15, verbose_name='\u9762\u79ef\u533a\u95f4')),
                ('open_date', models.DateField(verbose_name='\u5f00\u76d8\u65f6\u95f4')),
                ('detail_url', models.CharField(max_length=100, verbose_name='\u8be6\u60c5\u94fe\u63a5')),
                ('phone', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('price', models.FloatField(verbose_name='\u4ef7\u683c(\u5143)')),
            ],
            options={
                'verbose_name': '\u697c\u76d8\u5c55\u793a',
                'verbose_name_plural': '\u697c\u76d8\u5c55\u793a',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('one', '\u4e00\u5c45'), ('two', '\u4e8c\u5c45'), ('three', '\u4e09\u5c45'), ('four', '\u56db\u5c45'), ('five', '\u4e94\u5c45'), ('six', '\u4e94\u5c45\u4ee5\u4e0a')], max_length=10, verbose_name='\u6237\u578b')),
            ],
            options={
                'verbose_name': '\u697c\u76d8\u6237\u578b',
                'verbose_name_plural': '\u697c\u76d8\u6237\u578b',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.CharField(default='', max_length=200, verbose_name='\u94fe\u63a5')),
                ('news_name', models.CharField(default='', max_length=20, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb',
                'verbose_name_plural': '\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.ManyToManyField(blank=True, to='main.Building', verbose_name='\u5df2\u6536\u85cf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '\u7528\u6237\u4e2d\u5fc3', 'verbose_name_plural': '\u7528\u6237\u4e2d\u5fc3'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u4f4f\u5740'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='regions',
        ),
        migrations.AddField(
            model_name='profile',
            name='regions',
            field=models.CharField(blank=True, choices=[('qingyang', '\u9752\u7f8a'), ('jinniu', '\u91d1\u725b'), ('wuhou', '\u6b66\u4faf'), ('chenghua', '\u6210\u534e'), ('gaoxing', '\u9ad8\u65b0\u533a'), ('gaoxingxiqu', '\u9ad8\u65b0\u897f\u533a'), ('wenjaing', '\u6e29\u6c5f'), ('shuangliu', '\u53cc\u6d41'), ('longqianyi', '\u9f99\u6cc9\u9a7f'), ('xindu', '\u65b0\u90fd'), ('pixian', '\u90eb\u53bf'), ('dujiangyan', '\u90fd\u6c5f\u5830'), ('qingbaijiang', '\u9752\u767d\u6c5f'), ('pengzhou', '\u5f6d\u5dde'), ('pujiang', '\u6d66\u6c5f'), ('dayi', '\u5927\u9091'), ('xinjin', '\u65b0\u6d25'), ('zongzhou', '\u5d07\u5dde'), ('qonglai', '\u909b\u5d03'), ('jintang', '\u91d1\u5802')], max_length=10, verbose_name='\u610f\u5411\u533a\u57df'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='styles',
        ),
        migrations.AddField(
            model_name='profile',
            name='styles',
            field=models.CharField(blank=True, choices=[('one', '\u666e\u901a\u4f4f\u5b85'), ('two', '\u82b1\u56ed\u6d0b\u623f'), ('three', '\u522b\u5885'), ('four', '\u5546\u94fa'), ('five', '\u5199\u5b57\u697c'), ('six', '\u516c\u5bd3\uff09')], max_length=10, verbose_name='\u610f\u5411\u7c7b\u578b'),
        ),
        migrations.DeleteModel(
            name='LikeRegion',
        ),
        migrations.DeleteModel(
            name='LikeStyle',
        ),
        migrations.AddField(
            model_name='building',
            name='house_type',
            field=models.ManyToManyField(to='main.HouseType', verbose_name='\u6237\u578b'),
        ),
        migrations.AddField(
            model_name='banner',
            name='news_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.News'),
        ),
    ]
