# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, default='', upload_to=main.models.pic_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Activity')),
            ],
        ),
    ]
