# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-01 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170501_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_reset_password_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, choices=[('\u9526\u6c5f\u533a', '\u9526\u6c5f\u533a'), ('\u9752\u7f8a\u533a', '\u9752\u7f8a\u533a'), ('\u91d1\u725b\u533a', '\u91d1\u725b\u533a'), ('\u6b66\u4faf\u533a', '\u6b66\u4faf\u533a'), ('\u6210\u534e\u533a', '\u6210\u534e\u533a'), ('\u9ad8\u65b0\u533a', '\u9ad8\u65b0\u533a'), ('\u9ad8\u65b0\u897f\u533a', '\u9ad8\u65b0\u897f\u533a'), ('\u6e29\u6c5f', '\u6e29\u6c5f'), ('\u53cc\u6d41', '\u53cc\u6d41'), ('\u9f99\u6cc9\u9a7f', '\u9f99\u6cc9\u9a7f'), ('\u65b0\u90fd', '\u65b0\u90fd'), ('\u90eb\u53bf', '\u90eb\u53bf'), ('\u90fd\u6c5f\u5830', '\u90fd\u6c5f\u5830'), ('\u9752\u767d\u6c5f', '\u9752\u767d\u6c5f'), ('\u5f6d\u5dde', '\u5f6d\u5dde'), ('\u6d66\u6c5f', '\u6d66\u6c5f'), ('\u5927\u9091', '\u5927\u9091'), ('\u65b0\u6d25', '\u65b0\u6d25'), ('\u5d07\u5dde', '\u5d07\u5dde'), ('\u909b\u5d03', '\u909b\u5d03'), ('\u91d1\u5802', '\u91d1\u5802')], max_length=70, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regions',
            field=models.CharField(blank=True, choices=[('\u9526\u6c5f\u533a', '\u9526\u6c5f\u533a'), ('\u9752\u7f8a\u533a', '\u9752\u7f8a\u533a'), ('\u91d1\u725b\u533a', '\u91d1\u725b\u533a'), ('\u6b66\u4faf\u533a', '\u6b66\u4faf\u533a'), ('\u6210\u534e\u533a', '\u6210\u534e\u533a'), ('\u9ad8\u65b0\u533a', '\u9ad8\u65b0\u533a'), ('\u9ad8\u65b0\u897f\u533a', '\u9ad8\u65b0\u897f\u533a'), ('\u6e29\u6c5f', '\u6e29\u6c5f'), ('\u53cc\u6d41', '\u53cc\u6d41'), ('\u9f99\u6cc9\u9a7f', '\u9f99\u6cc9\u9a7f'), ('\u65b0\u90fd', '\u65b0\u90fd'), ('\u90eb\u53bf', '\u90eb\u53bf'), ('\u90fd\u6c5f\u5830', '\u90fd\u6c5f\u5830'), ('\u9752\u767d\u6c5f', '\u9752\u767d\u6c5f'), ('\u5f6d\u5dde', '\u5f6d\u5dde'), ('\u6d66\u6c5f', '\u6d66\u6c5f'), ('\u5927\u9091', '\u5927\u9091'), ('\u65b0\u6d25', '\u65b0\u6d25'), ('\u5d07\u5dde', '\u5d07\u5dde'), ('\u909b\u5d03', '\u909b\u5d03'), ('\u91d1\u5802', '\u91d1\u5802')], max_length=10, verbose_name='\u610f\u5411\u533a\u57df'),
        ),
    ]
