# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-08 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170508_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectitem',
            name='keyword',
            field=models.CharField(blank=True, max_length=15, verbose_name='\u5173\u952e\u5b57'),
        ),
    ]
