# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170429_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '\u9876\u90e8\u5e7f\u544a', 'verbose_name_plural': '\u9876\u90e8\u5e7f\u544a'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u65b0\u95fb', 'verbose_name_plural': '\u65b0\u95fb'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='newslimk',
            new_name='newslink',
        ),
    ]
