# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-08 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collectitem_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectitem',
            name='keyword',
            field=models.CharField(blank=True, editable=False, max_length=15, verbose_name='\u5173\u952e\u5b57'),
        ),
    ]
