# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170430_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_id', models.CharField(choices=[('1', '\u4e00\u9897\u661f'), ('2', '\u4e24\u9897\u661f'), ('3', '\u4e09\u9897\u661f'), ('4', '\u56db\u9897\u661f'), ('5', '\u4e94\u9897\u661f')], max_length=10, verbose_name='\u63a8\u8350\u6307\u6570')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('cover', models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u5c01\u9762\u56fe')),
                ('detail_url', models.CharField(max_length=100, verbose_name='\u8be6\u60c5\u94fe\u63a5')),
                ('limit_num', models.IntegerField(verbose_name='\u4eba\u6570\u4e0a\u9650')),
            ],
            options={
                'verbose_name': '\u6d3b\u52a8\u5217\u8868',
                'verbose_name_plural': '\u6d3b\u52a8\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='CollectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='\u5b57\u6bb5\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u9700\u8981\u7528\u6237\u586b\u5199\u7684\u5b57\u6bb5',
                'verbose_name_plural': '\u9700\u8981\u7528\u6237\u586b\u5199\u7684\u5b57\u6bb5',
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u65b0\u95fb\u94fe\u63a5', 'verbose_name_plural': '\u65b0\u95fb\u94fe\u63a5'},
        ),
        migrations.AddField(
            model_name='activity',
            name='collect_item',
            field=models.ManyToManyField(to='main.CollectItem', verbose_name='\u8bf7\u9009\u62e9\u60a8\u60f3\u6536\u96c6\u7684\u7528\u6237\u4fe1\u606f'),
        ),
    ]
