# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170429_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='imgurl',
            new_name='news_img',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='imgname',
            new_name='news_name',
        ),
    ]
