# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-07 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170507_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participatorinfo',
            name='id_num',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
    ]
