# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170429_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='newslink',
            new_name='news_link',
        ),
    ]
