# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170508_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybanner',
            name='title',
        ),
        migrations.AddField(
            model_name='activitybanner',
            name='link',
            field=models.CharField(default='', max_length=50, verbose_name='\u6d3b\u52a8\u94fe\u63a5'),
        ),
    ]
