# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20170429_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('img', models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u56fe\u7247')),
                ('location', models.CharField(max_length=70, verbose_name='\u4f4d\u7f6e')),
                ('phone', models.CharField(max_length=11, verbose_name='\u7535\u8bdd')),
                ('price', models.FloatField(verbose_name='\u4ef7\u683c')),
            ],
            options={
                'verbose_name': '\u697c\u76d8\u5c55\u793a',
                'verbose_name_plural': '\u697c\u76d8\u5c55\u793a',
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.ManyToManyField(blank=True, to='main.Building', verbose_name='\u5df2\u6536\u85cf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to=main.models.pic_upload_path, verbose_name='\u56fe\u7247'),
        ),
    ]
