# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-30 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170430_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='collectitem',
            name='name',
            field=models.CharField(blank=True, choices=[('\u624b\u673a', '\u624b\u673a'), ('\u771f\u5b9e\u59d3\u540d', '\u771f\u5b9e\u59d3\u540d'), ('\u5e74\u9f84', '\u5e74\u9f84'), ('\u8054\u7cfb\u5730\u5740', '\u8054\u7cfb\u5730\u5740')], max_length=10, verbose_name='\u5b57\u6bb5\u540d\u79f0'),
        ),
    ]
