# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170429_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likeregion',
            options={'verbose_name': '\u610f\u5411\u533a\u57df', 'verbose_name_plural': '\u610f\u5411\u533a\u57df'},
        ),
        migrations.AlterModelOptions(
            name='likestyle',
            options={'verbose_name': '\u610f\u5411\u7c7b\u578b', 'verbose_name_plural': '\u610f\u5411\u7c7b\u578b'},
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1828008293, max_length=11, verbose_name='\u624b\u673a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4f4f\u5740'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '\u7537'), ('F', '\u5973')], max_length=1, null=True, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='main.LikeRegion', verbose_name='\u610f\u5411\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='styles',
            field=models.ManyToManyField(blank=True, null=True, to='main.LikeStyle', verbose_name='\u610f\u5411\u7c7b\u578b'),
        ),
    ]
