# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-30 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20170430_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u9f84')),
                ('address', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u53c2\u52a0\u8005\u4fe1\u606f',
                'verbose_name_plural': '\u53c2\u52a0\u8005\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='participator',
            field=models.ManyToManyField(to='main.ParticipatorInfo', verbose_name='\u62a5\u540d\u7528\u6237'),
        ),
    ]
