# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-07 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170507_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='form_link',
            field=models.CharField(blank=True, max_length=70, verbose_name='\u62a5\u540d\u8868\u94fe\u63a5'),
        ),
    ]
