# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-07 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170507_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybanner',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitybanner',
            name='recommend_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u63a8\u8350\u6307\u6570(\u586b\u5199\uff1a1\u30012\u30013...)'),
        ),
        migrations.AddField(
            model_name='activitybanner',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='\u6807\u9898'),
        ),
    ]
