# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170429_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='regions',
            field=models.ManyToManyField(blank=True, to='main.LikeRegion', verbose_name='\u610f\u5411\u533a\u57df'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='styles',
            field=models.ManyToManyField(blank=True, to='main.LikeStyle', verbose_name='\u610f\u5411\u7c7b\u578b'),
        ),
    ]
