# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170507_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitybanner',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
