# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170430_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(to='main.Building', verbose_name='\u6536\u85cf\u7684\u697c\u76d8'),
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
