# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170429_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_img',
        ),
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.CharField(default='', max_length=200, verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(choices=[('qingyang', '\u9752\u7f8a'), ('jinniu', '\u91d1\u725b'), ('wuhou', '\u6b66\u4faf'), ('chenghua', '\u6210\u534e'), ('gaoxing', '\u9ad8\u65b0\u533a'), ('gaoxingxiqu', '\u9ad8\u65b0\u897f\u533a'), ('wenjaing', '\u6e29\u6c5f'), ('shuangliu', '\u53cc\u6d41'), ('longqianyi', '\u9f99\u6cc9\u9a7f'), ('xindu', '\u65b0\u90fd'), ('pixian', '\u90eb\u53bf'), ('dujiangyan', '\u90fd\u6c5f\u5830'), ('qingbaijiang', '\u9752\u767d\u6c5f'), ('pengzhou', '\u5f6d\u5dde'), ('pujiang', '\u6d66\u6c5f'), ('dayi', '\u5927\u9091'), ('xinjin', '\u65b0\u6d25'), ('zongzhou', '\u5d07\u5dde'), ('qonglai', '\u909b\u5d03'), ('jintang', '\u91d1\u5802')], max_length=70, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='building',
            name='price',
            field=models.CharField(choices=[('one', '3000\u4ee5\u4e0b'), ('two', '3000-5000'), ('three', '5000-7000'), ('four', '7000-9000'), ('five', '9000-11000'), ('size', '11000-15000'), ('seven', '15000-20000'), ('eight', '20000\u4ee5\u4e0a')], max_length=20, verbose_name='\u4ef7\u683c'),
        ),
    ]
